/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author hasalashehan
 */
public class JavaMainGUI extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private JButton currentActiveButton = null;



    /**
     * Creates new form JavaMainGUI
     */
    public JavaMainGUI() {
        initComponents();

        // Initialize the CardLayout
        cardLayout = (CardLayout) mainContainerPanel.getLayout();

        // Set initial active button (Profile)
        currentActiveButton = profileButton;
        profileButton.setEnabled(false);
    }

    private void navigateToCard(JButton button, String cardName) {
        // Enable the previously active button
        if (currentActiveButton != null) {
            currentActiveButton.setEnabled(true);
        }

        // Disable the current button and show the corresponding card
        button.setEnabled(false);
        currentActiveButton = button;
        cardLayout.show(mainContainerPanel, cardName);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonSetPanel = new javax.swing.JPanel();
        courseButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        noticeButton = new javax.swing.JButton();
        timeTableButton = new javax.swing.JButton();
        editProfileButton = new javax.swing.JButton();
        mainContainerPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profileHeadingName = new javax.swing.JLabel();
        detailsPanel = new javax.swing.JPanel();
        detailsName = new javax.swing.JLabel();
        detailsAddress = new javax.swing.JLabel();
        detailsMail = new javax.swing.JLabel();
        detailsPNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proPicPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        coursesStuPanel = new javax.swing.JPanel();
        coursesHeadingLabel = new javax.swing.JLabel();
        dsaButton = new javax.swing.JButton();
        OOPPracButton = new javax.swing.JButton();
        OODAButton = new javax.swing.JButton();
        eComButton = new javax.swing.JButton();
        OOPButton = new javax.swing.JButton();
        noticePanel = new javax.swing.JPanel();
        noticeHeadingLabel = new javax.swing.JLabel();
        noticeScrollPane = new javax.swing.JScrollPane();
        noticeTable = new javax.swing.JTable();
        timeTablePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1034, 778));
        setPreferredSize(new java.awt.Dimension(2000, 1000));

        basePanel.setBackground(new java.awt.Color(255, 255, 255));
        basePanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        basePanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        basePanel.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(0, 74, 173));

        jLabel1.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Student Management System");

        jLabel2.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Faculty of Technology University of Ruhuna");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Log Out");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addContainerGap(266, Short.MAX_VALUE))
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))))
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        basePanel.add(headerPanel);
        headerPanel.setBounds(6, 6, 1000, 110);

        buttonSetPanel.setBackground(new java.awt.Color(0, 74, 173));

        courseButton.setBackground(new java.awt.Color(0, 74, 173));
        courseButton.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        courseButton.setForeground(new java.awt.Color(255, 255, 255));
        courseButton.setText("Courses");
        courseButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 102, 255), null, null));

        profileButton.setBackground(new java.awt.Color(0, 74, 173));
        profileButton.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setText("Profile");
        profileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 102, 255), null, null));

        noticeButton.setBackground(new java.awt.Color(0, 74, 173));
        noticeButton.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        noticeButton.setForeground(new java.awt.Color(255, 255, 255));
        noticeButton.setText("Notices");
        noticeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 102, 255), null, null));

        timeTableButton.setBackground(new java.awt.Color(0, 74, 173));
        timeTableButton.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        timeTableButton.setForeground(new java.awt.Color(255, 255, 255));
        timeTableButton.setText("Time Table");
        timeTableButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 102, 255), null, null));

        editProfileButton.setBackground(new java.awt.Color(0, 74, 173));
        editProfileButton.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        editProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        editProfileButton.setText("Edit Profile");
        editProfileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 102, 255), null, null));
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonSetPanelLayout = new javax.swing.GroupLayout(buttonSetPanel);
        buttonSetPanel.setLayout(buttonSetPanelLayout);
        buttonSetPanelLayout.setHorizontalGroup(
                buttonSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonSetPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(buttonSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(courseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(noticeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(timeTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(profileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addContainerGap())
        );
        buttonSetPanelLayout.setVerticalGroup(
                buttonSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonSetPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(courseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noticeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timeTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203))
        );

        basePanel.add(buttonSetPanel);
        buttonSetPanel.setBounds(6, 116, 198, 630);

        mainContainerPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 74, 173), 3));
        mainContainerPanel.setLayout(new java.awt.CardLayout());

        profileHeadingName.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        profileHeadingName.setText("Profile");

        detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        detailsName.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        detailsName.setForeground(new java.awt.Color(255, 204, 51));
        detailsName.setText("Hi Hasala");

        detailsAddress.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        detailsAddress.setForeground(new java.awt.Color(102, 102, 102));
        detailsAddress.setText("Address");

        detailsMail.setFont(new java.awt.Font("ITF Devanagari", 2, 18)); // NOI18N
        detailsMail.setText("Email");

        detailsPNo.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        detailsPNo.setText("Phone Number");

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        jLabel3.setText("Role");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
                detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(detailsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(detailsAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(detailsMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(detailsPNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(69, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
                detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(detailsName)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(detailsAddress)
                                .addGap(18, 18, 18)
                                .addComponent(detailsMail)
                                .addGap(18, 18, 18)
                                .addComponent(detailsPNo)
                                .addContainerGap(77, Short.MAX_VALUE))
        );

        proPicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 74, 173), 2));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("No Profile Pic");

        javax.swing.GroupLayout proPicPanelLayout = new javax.swing.GroupLayout(proPicPanel);
        proPicPanel.setLayout(proPicPanelLayout);
        proPicPanelLayout.setHorizontalGroup(
                proPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(proPicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addContainerGap())
        );
        proPicPanelLayout.setVerticalGroup(
                proPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(proPicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(profilePanelLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(profileHeadingName))
                                        .addGroup(profilePanelLayout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(proPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(55, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(profileHeadingName)
                                .addGap(66, 66, 66)
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(proPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(127, Short.MAX_VALUE))
        );

        mainContainerPanel.add(profilePanel, "card2");

        coursesStuPanel.setBackground(new java.awt.Color(255, 255, 255));

        coursesHeadingLabel.setFont(new java.awt.Font("Krungthep", 1, 36)); // NOI18N
        coursesHeadingLabel.setText("Courses");

        dsaButton.setBackground(new java.awt.Color(0, 153, 204));
        dsaButton.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        dsaButton.setForeground(new java.awt.Color(255, 255, 255));
        dsaButton.setText("Data Structures and Algorithms");
        dsaButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 204), null));

        OOPPracButton.setBackground(new java.awt.Color(0, 153, 204));
        OOPPracButton.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        OOPPracButton.setForeground(new java.awt.Color(255, 255, 255));
        OOPPracButton.setText("Object Oriented Programming Practicum");
        OOPPracButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), null));

        OODAButton.setBackground(new java.awt.Color(0, 153, 204));
        OODAButton.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        OODAButton.setForeground(new java.awt.Color(255, 255, 255));
        OODAButton.setText("Object Oriented Design and Analysis");
        OODAButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), null));

        eComButton.setBackground(new java.awt.Color(0, 153, 204));
        eComButton.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        eComButton.setForeground(new java.awt.Color(255, 255, 255));
        eComButton.setText("E-Commerce Implementation, Management and Security");
        eComButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), null));

        OOPButton.setBackground(new java.awt.Color(0, 153, 204));
        OOPButton.setFont(new java.awt.Font("Kefa", 1, 12)); // NOI18N
        OOPButton.setForeground(new java.awt.Color(255, 255, 255));
        OOPButton.setText("Object Oreinted Programming ");
        OOPButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), null));

        javax.swing.GroupLayout coursesStuPanelLayout = new javax.swing.GroupLayout(coursesStuPanel);
        coursesStuPanel.setLayout(coursesStuPanelLayout);
        coursesStuPanelLayout.setHorizontalGroup(
                coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(coursesStuPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(coursesHeadingLabel)
                                .addGap(71, 71, 71))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesStuPanelLayout.createSequentialGroup()
                                .addContainerGap(82, Short.MAX_VALUE)
                                .addGroup(coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(OOPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(coursesStuPanelLayout.createSequentialGroup()
                                                        .addComponent(eComButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(OOPPracButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(coursesStuPanelLayout.createSequentialGroup()
                                                        .addComponent(dsaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(OODAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(94, 94, 94))
        );
        coursesStuPanelLayout.setVerticalGroup(
                coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(coursesStuPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(coursesHeadingLabel)
                                .addGap(79, 79, 79)
                                .addGroup(coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dsaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(OODAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(coursesStuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eComButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(OOPPracButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(OOPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
        );

        mainContainerPanel.add(coursesStuPanel, "card3");

        noticeHeadingLabel.setFont(new java.awt.Font("Krungthep", 1, 36)); // NOI18N
        noticeHeadingLabel.setText("Notices");

        noticeTable.setMaximumSize(new java.awt.Dimension(300, 80));
        noticeScrollPane.setViewportView(noticeTable);

        javax.swing.GroupLayout noticePanelLayout = new javax.swing.GroupLayout(noticePanel);
        noticePanel.setLayout(noticePanelLayout);
        noticePanelLayout.setHorizontalGroup(
                noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(noticePanelLayout.createSequentialGroup()
                                .addGroup(noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(noticePanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(noticeHeadingLabel))
                                        .addGroup(noticePanelLayout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(noticeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(152, Short.MAX_VALUE))
        );
        noticePanelLayout.setVerticalGroup(
                noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(noticePanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(noticeHeadingLabel)
                                .addGap(61, 61, 61)
                                .addComponent(noticeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainContainerPanel.add(noticePanel, "card4");

        jLabel5.setFont(new java.awt.Font("Krungthep", 1, 36)); // NOI18N
        jLabel5.setText("Time Table");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout timeTablePanelLayout = new javax.swing.GroupLayout(timeTablePanel);
        timeTablePanel.setLayout(timeTablePanelLayout);
        timeTablePanelLayout.setHorizontalGroup(
                timeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(timeTablePanelLayout.createSequentialGroup()
                                .addGroup(timeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(timeTablePanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel5))
                                        .addGroup(timeTablePanelLayout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(131, Short.MAX_VALUE))
        );
        timeTablePanelLayout.setVerticalGroup(
                timeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(timeTablePanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainContainerPanel.add(timeTablePanel, "card5");

        basePanel.add(mainContainerPanel);
        mainContainerPanel.setBounds(210, 120, 800, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        // Add action listeners to navigation buttons
        profileButton.addActionListener(e -> navigateToCard(profileButton, "card2"));
        courseButton.addActionListener(e -> navigateToCard(courseButton, "card3"));
        noticeButton.addActionListener(e -> navigateToCard(noticeButton, "card4"));
        timeTableButton.addActionListener(e -> navigateToCard(timeTableButton, "card5"));
        editProfileButton.addActionListener(e -> navigateToCard(editProfileButton, "card6")); // Add this if you have an edit profile card

// Logout button action
        jButton1.addActionListener(e -> System.exit(0));

        pack();
    }// </editor-fold>



    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JavaMainGUI frame = new JavaMainGUI();
                frame.setLocationRelativeTo(null); // This line will center the JFrame
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton OODAButton;
    private javax.swing.JButton OOPButton;
    private javax.swing.JButton OOPPracButton;
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel buttonSetPanel;
    private javax.swing.JButton courseButton;
    private javax.swing.JLabel coursesHeadingLabel;
    private javax.swing.JPanel coursesStuPanel;
    private javax.swing.JLabel detailsAddress;
    private javax.swing.JLabel detailsMail;
    private javax.swing.JLabel detailsName;
    private javax.swing.JLabel detailsPNo;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JButton dsaButton;
    private javax.swing.JButton eComButton;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainContainerPanel;
    private javax.swing.JButton noticeButton;
    private javax.swing.JLabel noticeHeadingLabel;
    private javax.swing.JPanel noticePanel;
    private javax.swing.JScrollPane noticeScrollPane;
    private javax.swing.JTable noticeTable;
    private javax.swing.JPanel proPicPanel;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel profileHeadingName;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton timeTableButton;
    private javax.swing.JPanel timeTablePanel;
    // End of variables declaration
}
